  const ACTIONS = {
    LOAD_BOOKS: 'LOAD_BOOKS',
    SELECT_BOOK: 'SELECT_BOOK',
    ADD_BOOK: 'ADD_BOOK',
    NEW_BOOK: 'NEW_BOOK',
    EDIT_BOOK: 'EDIT_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',
    SHOW_BOOK_MODAL: 'SHOW_BOOK_MODAL',
    HIDE_BOOK_MODAL: 'HIDE_BOOK_MODAL',
    SHOW_CONFIRM_MODAL: 'SHOW_CONFIRM_MODAL',
    HIDE_CONFIRM_MODAL: 'HIDE_CONFIRM_MODAL',
}

 const BOOK_MODAL_MODES = {
    CREATE_NEW_BOOK: 'CREATE NEW BOOK',
    EDIT_BOOK: 'EDIT BOOK'
}

export { 
    ACTIONS, BOOK_MODAL_MODES
}